question_data = [
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
    "question": "The HTML5 standard was published in 2014.", "correct_answer": "True",
    "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
    "question": "The first computer bug was formed by faulty wires.",
    "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
    "question": "FLAC stands for 'Free Lossless Audio Condenser'",
    "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
    "question": "The very first recorded computer 'bug' was a moth "
    "found inside a Harvard Mark II computer.",
    "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
    "question": "'Windows NT' is a monolithic kernel.",
    "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
    "question": "To bypass US Munitions Export Laws, the creator of the PGP "
    "published all the source code in book form. ",
    "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
    "question": "MacOS is based on Linux.", "correct_answer": "False",
    "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
    "question": "The first dual-core CPU was the Intel Pentium D.",
    "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
    "question": "It's not possible to format a write-protected DVD-R Hard Disk.",
    "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
    "question": "Linus Sebastian is the creator of the Linux kernel, "
    "which went on to be used in Linux, Android, and Chrome OS.",
    "correct_answer": "False", "incorrect_answers": ["True"]}
]
